[package]
name = "vpt-lazy-ripoff"
authors = ["Gorazd Gorup", "Žiga Lesar"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.18", features = ["derive", "cargo"]}
wgpu = {version = "0.14.0", features = ["spirv"]}
futures-intrusive = "0.4.1"
pollster = "0.2.5"
bytemuck = {version = "1.12.1", features = [ "derive" ]}
rand = "0.8.5"